/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as BureauRouteImport } from './routes/bureau'
import { Route as CaravanesRouteImport } from './routes/caravanes'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as GalerieRouteImport } from './routes/galerie'
import { Route as HistoireRouteImport } from './routes/histoire'
import { Route as MissionsRouteImport } from './routes/missions'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as BilletIdRouteImport } from './routes/billet.$id'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin.index'
import { Route as AuthenticatedAdminEvenementsRouteImport } from './routes/_authenticated/admin.evenements'
import { Route as AuthenticatedAdminScanRouteImport } from './routes/_authenticated/admin.scan'
import { Route as AuthenticatedAdminUtilisateursRouteImport } from './routes/_authenticated/admin.utilisateurs'
import { Route as ApiPublicPaytechIpnRouteImport } from './routes/api/public/paytech-ipn'
import { Route as AuthenticatedAdminCaravanesIndexRouteImport } from './routes/_authenticated/admin.caravanes.index'
import { Route as AuthenticatedAdminCaravanesIdRouteImport } from './routes/_authenticated/admin.caravanes.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const BureauRoute = BureauRouteImport.update({
  id: '/bureau',
  path: '/bureau',
  getParentRoute: () => rootRouteImport,
} as any)
const CaravanesRoute = CaravanesRouteImport.update({
  id: '/caravanes',
  path: '/caravanes',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const GalerieRoute = GalerieRouteImport.update({
  id: '/galerie',
  path: '/galerie',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoireRoute = HistoireRouteImport.update({
  id: '/histoire',
  path: '/histoire',
  getParentRoute: () => rootRouteImport,
} as any)
const MissionsRoute = MissionsRouteImport.update({
  id: '/missions',
  path: '/missions',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const BilletIdRoute = BilletIdRouteImport.update({
  id: '/billet/$id',
  path: '/billet/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminEvenementsRoute =
  AuthenticatedAdminEvenementsRouteImport.update({
    id: '/evenements',
    path: '/evenements',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminScanRoute = AuthenticatedAdminScanRouteImport.update({
  id: '/scan',
  path: '/scan',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminUtilisateursRoute =
  AuthenticatedAdminUtilisateursRouteImport.update({
    id: '/utilisateurs',
    path: '/utilisateurs',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const ApiPublicPaytechIpnRoute = ApiPublicPaytechIpnRouteImport.update({
  id: '/api/public/paytech-ipn',
  path: '/api/public/paytech-ipn',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminCaravanesIndexRoute =
  AuthenticatedAdminCaravanesIndexRouteImport.update({
    id: '/caravanes/',
    path: '/caravanes/',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminCaravanesIdRoute =
  AuthenticatedAdminCaravanesIdRouteImport.update({
    id: '/caravanes/$id',
    path: '/caravanes/$id',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/bureau': typeof BureauRoute
  '/caravanes': typeof CaravanesRoute
  '/contact': typeof ContactRoute
  '/galerie': typeof GalerieRoute
  '/histoire': typeof HistoireRoute
  '/missions': typeof MissionsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/billet/$id': typeof BilletIdRoute
  '/admin/evenements': typeof AuthenticatedAdminEvenementsRoute
  '/admin/scan': typeof AuthenticatedAdminScanRoute
  '/admin/utilisateurs': typeof AuthenticatedAdminUtilisateursRoute
  '/api/public/paytech-ipn': typeof ApiPublicPaytechIpnRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/admin/caravanes/$id': typeof AuthenticatedAdminCaravanesIdRoute
  '/admin/caravanes/': typeof AuthenticatedAdminCaravanesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/bureau': typeof BureauRoute
  '/caravanes': typeof CaravanesRoute
  '/contact': typeof ContactRoute
  '/galerie': typeof GalerieRoute
  '/histoire': typeof HistoireRoute
  '/missions': typeof MissionsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/billet/$id': typeof BilletIdRoute
  '/admin/evenements': typeof AuthenticatedAdminEvenementsRoute
  '/admin/scan': typeof AuthenticatedAdminScanRoute
  '/admin/utilisateurs': typeof AuthenticatedAdminUtilisateursRoute
  '/api/public/paytech-ipn': typeof ApiPublicPaytechIpnRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/admin/caravanes/$id': typeof AuthenticatedAdminCaravanesIdRoute
  '/admin/caravanes': typeof AuthenticatedAdminCaravanesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/bureau': typeof BureauRoute
  '/caravanes': typeof CaravanesRoute
  '/contact': typeof ContactRoute
  '/galerie': typeof GalerieRoute
  '/histoire': typeof HistoireRoute
  '/missions': typeof MissionsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/billet/$id': typeof BilletIdRoute
  '/_authenticated/admin/evenements': typeof AuthenticatedAdminEvenementsRoute
  '/_authenticated/admin/scan': typeof AuthenticatedAdminScanRoute
  '/_authenticated/admin/utilisateurs': typeof AuthenticatedAdminUtilisateursRoute
  '/api/public/paytech-ipn': typeof ApiPublicPaytechIpnRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/admin/caravanes/$id': typeof AuthenticatedAdminCaravanesIdRoute
  '/_authenticated/admin/caravanes/': typeof AuthenticatedAdminCaravanesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/bureau'
    | '/caravanes'
    | '/contact'
    | '/galerie'
    | '/histoire'
    | '/missions'
    | '/sitemap.xml'
    | '/admin'
    | '/billet/$id'
    | '/admin/evenements'
    | '/admin/scan'
    | '/admin/utilisateurs'
    | '/api/public/paytech-ipn'
    | '/admin/'
    | '/admin/caravanes/$id'
    | '/admin/caravanes/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/bureau'
    | '/caravanes'
    | '/contact'
    | '/galerie'
    | '/histoire'
    | '/missions'
    | '/sitemap.xml'
    | '/billet/$id'
    | '/admin/evenements'
    | '/admin/scan'
    | '/admin/utilisateurs'
    | '/api/public/paytech-ipn'
    | '/admin'
    | '/admin/caravanes/$id'
    | '/admin/caravanes'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/bureau'
    | '/caravanes'
    | '/contact'
    | '/galerie'
    | '/histoire'
    | '/missions'
    | '/sitemap.xml'
    | '/_authenticated/admin'
    | '/billet/$id'
    | '/_authenticated/admin/evenements'
    | '/_authenticated/admin/scan'
    | '/_authenticated/admin/utilisateurs'
    | '/api/public/paytech-ipn'
    | '/_authenticated/admin/'
    | '/_authenticated/admin/caravanes/$id'
    | '/_authenticated/admin/caravanes/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  BureauRoute: typeof BureauRoute
  CaravanesRoute: typeof CaravanesRoute
  ContactRoute: typeof ContactRoute
  GalerieRoute: typeof GalerieRoute
  HistoireRoute: typeof HistoireRoute
  MissionsRoute: typeof MissionsRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  BilletIdRoute: typeof BilletIdRoute
  ApiPublicPaytechIpnRoute: typeof ApiPublicPaytechIpnRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bureau': {
      id: '/bureau'
      path: '/bureau'
      fullPath: '/bureau'
      preLoaderRoute: typeof BureauRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/caravanes': {
      id: '/caravanes'
      path: '/caravanes'
      fullPath: '/caravanes'
      preLoaderRoute: typeof CaravanesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/galerie': {
      id: '/galerie'
      path: '/galerie'
      fullPath: '/galerie'
      preLoaderRoute: typeof GalerieRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/histoire': {
      id: '/histoire'
      path: '/histoire'
      fullPath: '/histoire'
      preLoaderRoute: typeof HistoireRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/missions': {
      id: '/missions'
      path: '/missions'
      fullPath: '/missions'
      preLoaderRoute: typeof MissionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/billet/$id': {
      id: '/billet/$id'
      path: '/billet/$id'
      fullPath: '/billet/$id'
      preLoaderRoute: typeof BilletIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/evenements': {
      id: '/_authenticated/admin/evenements'
      path: '/evenements'
      fullPath: '/admin/evenements'
      preLoaderRoute: typeof AuthenticatedAdminEvenementsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/scan': {
      id: '/_authenticated/admin/scan'
      path: '/scan'
      fullPath: '/admin/scan'
      preLoaderRoute: typeof AuthenticatedAdminScanRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/utilisateurs': {
      id: '/_authenticated/admin/utilisateurs'
      path: '/utilisateurs'
      fullPath: '/admin/utilisateurs'
      preLoaderRoute: typeof AuthenticatedAdminUtilisateursRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/api/public/paytech-ipn': {
      id: '/api/public/paytech-ipn'
      path: '/api/public/paytech-ipn'
      fullPath: '/api/public/paytech-ipn'
      preLoaderRoute: typeof ApiPublicPaytechIpnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/caravanes/': {
      id: '/_authenticated/admin/caravanes/'
      path: '/caravanes'
      fullPath: '/admin/caravanes/'
      preLoaderRoute: typeof AuthenticatedAdminCaravanesIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/caravanes/$id': {
      id: '/_authenticated/admin/caravanes/$id'
      path: '/caravanes/$id'
      fullPath: '/admin/caravanes/$id'
      preLoaderRoute: typeof AuthenticatedAdminCaravanesIdRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
  }
}

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminEvenementsRoute: typeof AuthenticatedAdminEvenementsRoute
  AuthenticatedAdminScanRoute: typeof AuthenticatedAdminScanRoute
  AuthenticatedAdminUtilisateursRoute: typeof AuthenticatedAdminUtilisateursRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
  AuthenticatedAdminCaravanesIdRoute: typeof AuthenticatedAdminCaravanesIdRoute
  AuthenticatedAdminCaravanesIndexRoute: typeof AuthenticatedAdminCaravanesIndexRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminEvenementsRoute: AuthenticatedAdminEvenementsRoute,
  AuthenticatedAdminScanRoute: AuthenticatedAdminScanRoute,
  AuthenticatedAdminUtilisateursRoute: AuthenticatedAdminUtilisateursRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
  AuthenticatedAdminCaravanesIdRoute: AuthenticatedAdminCaravanesIdRoute,
  AuthenticatedAdminCaravanesIndexRoute: AuthenticatedAdminCaravanesIndexRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  BureauRoute: BureauRoute,
  CaravanesRoute: CaravanesRoute,
  ContactRoute: ContactRoute,
  GalerieRoute: GalerieRoute,
  HistoireRoute: HistoireRoute,
  MissionsRoute: MissionsRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  BilletIdRoute: BilletIdRoute,
  ApiPublicPaytechIpnRoute: ApiPublicPaytechIpnRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
